// vue/Note.vue
<template>
  <div>
    <button v-on:click="onPlayStop">
      {{ this.isPlaying ? "Stop" : "Play"}}
    </button>
    <button v-on:click="onHigher">Higher</button>
    <button v-on:click="onLower">Lower</button>
    <button v-on:click="onReset">Reset</button>
    <div>{{ this.frequency }}</div>
  </div>
</template>

<script>
export default {
  name: 'Note',
  props: [
     'initialFrequency'
  ],
  data() {
    return {
      isPlaying: false,
      frequency: this.initialFrequency,
    }
  },
  methods: {
    initOscillator(frequency) {
      const audioContext = new AudioContext();
      const oscillator = audioContext.createOscillator();
      const gain = audioContext.createGain();
      gain.gain.value = 0.3;
      oscillator.connect(gain);
      gain.connect(audioContext.destination);
      oscillator.frequency.value = frequency;
      return oscillator;
    },
    onPlayStop() {
      if (this.isPlaying) {
        this.oscillator.stop();
        this.isPlaying = false;
      } else {
        this.oscillator = this.initOscillator(this.frequency);
        this.oscillator.start();
        this.isPlaying = true;
      }
    },
    oneSemiTone() {
      return Math.pow(2, 1/12);
    },
    startNewFrequency(newFrequency) {
      this.frequency = newFrequency;
      if (this.isPlaying) {
        this.oscillator.stop();
      }
      this.oscillator = this.initOscillator(newFrequency);
      this.oscillator.start();
      this.isPlaying = true;
    },
    onHigher() {
      this.startNewFrequency(this.frequency * this.oneSemiTone());
    },
    onLower() {
      this.startNewFrequency(this.frequency / this.oneSemiTone());
    },
    onReset() {
      this.startNewFrequency(this.initialFrequency);
    }
  }
}
</script>

// svelte/Note.svelte
<script>
export let initialFrequency;  // Prop
const audioContext = new AudioContext();
let frequency = initialFrequency;
let oscillator = initOscillator(frequency);  // Just gets tossed...
let isPlaying = false;

function initOscillator(frequency) {
  const oscillator = audioContext.createOscillator();
  const gain = audioContext.createGain();
  gain.gain.value = 0.3;
  oscillator.connect(gain);
  gain.connect(audioContext.destination);
  oscillator.frequency.value = frequency;
  return oscillator;
}

function onPlayStop(event) {
  if (isPlaying) {
    oscillator.stop();
    isPlaying = false;
  } else {
    oscillator = initOscillator(frequency);
    oscillator.start();
    isPlaying = true;
  }
}

function startNewFrequency(newFrequency) {
  frequency = newFrequency;
  if (isPlaying) {
    oscillator.stop();
  }
  oscillator = initOscillator(frequency);
  oscillator.start();
  isPlaying = true;
}

function oneSemiTone() {
  return Math.pow(2, 1/12);
}

function onHigher(event) {
  startNewFrequency(frequency * oneSemiTone());
}

function onLower(event) {
  startNewFrequency(frequency / oneSemiTone());
}

function onReset(event) {
  startNewFrequency(initialFrequency);
}

</script>

<button on:click={onPlayStop}>
  { isPlaying ? 'Stop' : 'Play' }
</button>
<button on:click={onHigher}>Higher</button>
<button on:click={onLower}>Lower</button>
<button on:click={onReset}>Reset</button>
